Feature/javier
miquelg3/GDDProjecte3D pull request #20
Opened 2024-05-03 15:23 UTC by SorakiShirotsubasa

Añadiendo IAJEFE1 con una escena en la carpeta prefabs y organizando todo lo de la rama Feature/Javier en la nueva jerarquía de carpetas nuevas

2024-05-03 15:28 UTC, MoraCamarasa commented
No funciona el NavMesh en la escena IAJefe1 >:(

2024-05-03 15:47 UTC, SorakiShirotsubasa commented
He solucionado los problemas requeridos de revisión por Victor Camarasa

2024-05-03 16:03 UTC, SorakiShirotsubasa commented
![image](https://github.com/miquelg3/GDDProjecte3D/assets/47535813/7862bba1-0df5-4fa2-b4f0-393bd81a6fa0)
![image](https://github.com/miquelg3/GDDProjecte3D/assets/47535813/a86d041a-3406-4bf5-b3d8-106813a893d8)
Solventadme esto @Crisstxt @miquelg3

2024-05-05 10:01 UTC, sukifree commented on Unity/BrokenFaith/Assets/Prefabs/CuchilloLow.blend
No puedo validar la escena porque no tengo instalado Blender y por tanto no me detecta la malla del cuchillo, indicando que el "MeshFilter" del prefab "cuchilloLow" está "missing". Soluciona esto convirtiendo el blend en FBX y corrige el prefab.

2024-05-05 10:01 UTC, sukifree requested changes
No puedo validar la escena porque no tengo instalado Blender y por tanto no me detecta la malla del cuchillo, indicando que el "MeshFilter" del prefab "cuchilloLow" está "missing". Soluciona esto convirtiendo el blend en FBX y corrige el prefab.

2024-05-06 14:41 UTC, SorakiShirotsubasa commented
Solventado los cambios requeridos acerca del modelo, esta en el ultimo commit de la Rama Feature/Javier

2024-05-06 15:58 UTC, sukifree commented on Unity/BrokenFaith/Assets/Cristobal/Scenes/Blocking + NavMesh  Mapa1.unity
La escena no se debe modificar, ya que la gente de diseño (Víctor y Quique) están modificándola y habrá conflictos.

2024-05-06 15:58 UTC, sukifree requested changes
Tienes que traerte primero la rama de main a tu rama y luego pedir PR.

2024-05-06 16:11 UTC, SorakiShirotsubasa commented
ya me he traido main a mi rama

2024-05-06 16:16 UTC, sukifree approved these changes

2024-05-06 16:17 UTC, merged