Props Tuneles
miquelg3/GDDProjecte3D pull request #21
Opened 2024-05-03 19:03 UTC by MoraCamarasa

Añadidos los props posibles a los túneles. He ideado que hubieran piedras en las paredes y a lo largo de los túneles para dar el look de mina/excavación e intentar que sea una escena lo más rica y natural posible visualmente. Hacen falta un par de props más como herramientas, las correspondientes antorchas y por ejemplo, alguna carretilla(como para transportar lo extraído)

También hay alguna modificación de variedad de prefabs hecho por Alejandro.

El suelo se ha cambiado al material de tierra.

2024-05-05 10:18 UTC, sukifree requested changes
En la carpeta Models/Scene1Ermita/SM_Escalera_Piedra -> el material "Material" debería estar en raíz de esta carpeta y no dentro de "Backtracking", ya que es el material del SM_Escalera_Piedra y no del Backtracking.
El prefab "SM_Escalera_Piedra Variant" debería tener su transform en la posición (0,0,0) para poder ubicarlo mejor (resetear su transform).

Por otra parte, el prefab "SM_Arco_Ermita" que está en Prefabs/Scene1Ermita/Enviro/Suelos tiene asignado un material que por defecto no se puede editar (viene dado por Universal RP, es un ejemplo), ese material debería estar creado y asignado en la carpeta de su correspondiente modelo 3D, es decir, en Models/Scene1Ermita/SM_Arco_Ermita.

Al prefab "SM_Plano" que está en Prefabs/Scene1Ermita/Enviro/Suelos le pasa lo mismo que a SM_Escalera_Piedra, su material no corresponde al que debería estar puesto en la carpeta de Models/Scene1Ermita/SM_Plano (que ahí hay un material).

Por último, el SM_Plano Variant, debería también estar su transform en posición (0,0,0), es decir, reseteado a su posición 0.

2024-05-06 11:53 UTC, MoraCamarasa commented
Feedback aplicado

2024-05-06 13:15 UTC, Ezterothz approved these changes
Vale luego en clase te doy un poco de feedback rapido pero prefiero comentarlo contigo antes, Yo por mi adelante, Good Work

2024-05-06 17:12 UTC, sukifree approved these changes

2024-05-06 17:16 UTC, merged