Feature/montaje final
miquelg3/GDDProjecte3D pull request #24
Opened 2024-05-07 17:10 UTC by MoraCamarasa

Añadido los prefabs del Arco y la Espada que precisaba Cristóbal en su respectiva carpeta <Armas> tanto en models y prefabs. El cuchillo low lo he añadido a Armas ya que estaba fuera. El Arco está SIN RIG.

2024-05-07 18:44 UTC, sukifree approved these changes
Ya te has acostumbrado a dejar ordenados las carpetas. Todo ok

2024-05-08 16:06 UTC, sukifree requested changes
No sé qué habéis hecho, pero fallan 65 prefabs. 
![Montaje Final](https://github.com/miquelg3/GDDProjecte3D/assets/9253832/09c6186a-8c43-462e-98c9-d7b940a903a6)

2024-05-08 16:16 UTC, MoraCamarasa commented
Eso es de mi carpeta Victor eliminada, con los modelos antiguos y escenas obsoletas.
Por lo que creo, no hay mayor problema que la escena que utilizaba cristobal para probar el navmesh hasta que se crease el mapa definitivo era una de esas.

2024-05-08 16:37 UTC, sukifree commented
> Eso es de mi carpeta Victor eliminada, con los modelos antiguos y escenas obsoletas. Por lo que creo, no hay mayor problema que la escena que utilizaba cristobal para probar el navmesh hasta que se crease el mapa definitivo era una de esas.

Puedes entonces añadir la escena principal a Build Settings (la que estabas haciendo) y la main? y eliminar todas las demás (por favor?)

2024-05-08 16:37 UTC, sukifree approved these changes

2024-05-09 15:02 UTC, sukifree approved these changes

2024-05-09 15:06 UTC, merged