Feat: Prefab de player VR con interacciones de sockets (coger y dejar...
miquelg3/GDDProjecte3D pull request #27
Opened 2024-05-10 14:54 UTC by miquelg3

… objetos en perchas para a posteriori integrarlo en el inventario VR)

2024-05-10 15:06 UTC, sukifree approved these changes

2024-05-10 15:16 UTC, MoraCamarasa commented
La funcionalidad está conseguida y hace su proposito, pero hay varios bugs: 
-El sombrero mexicano, cuando le apuntas el raycast vuelve hacia ti como el Mjolnir a Thor, muy basto.
-Se pueden superponer 2 sombreros a la vez en la misma mano.
-Cuando pasas la mano cerca de un sombrero en una percha, accidentalmente lo puedes pillar sin apretar el gatillo.
Aprobado el PR.

2024-05-10 15:16 UTC, MoraCamarasa approved these changes

2024-05-10 15:20 UTC, Ezterothz approved these changes
Funciona como se quería. Aun así hay mejoras como las que ha comentado Victor de implementar. La única petición que me gustaría probar seria la de añadirle un socket al jugador.

2024-05-11 20:02 UTC, sukifree requested changes
Revisa el comentario de Victor y haz las modificaciones necesarias, entonces aceptaré el PR.
Deberían estar los cambios para el lunes o el martes a muy tardar.
Hay que ponerse con el inventario para el viernes probarlo.

2024-05-13 15:34 UTC, sukifree commented
@miquelg3
![Captura](https://github.com/miquelg3/GDDProjecte3D/assets/9253832/064277fe-0b5d-47c6-83c9-6a50160f6aab)
-El prefab "HookHead" entiendo que es el "Hook" pero renombrado.
-El "HookHead" tiene color negro, ¿no debería NO tener MeshRenderer?
-Otra cosa es si la has probado en VR, en el vídeo no sé si estaba atachado a alguna parte de la cámara o sólo a la "Camara Offset".
-Por otro lado, una vez modificas el prefab del PlayerVR, tienes que hacer "overrides" para aplicar a todos los prefabs, porque sino solo estará en tu escena.

Edita la escena y quita el meshrenderer y guarda el prefab.

2024-05-13 17:12 UTC, miquelg3 commented
Solucionado los problemas del meshrenderer y el no haber guardado el prefab. Añadido un script que persigue la cámara del jugador para que al ponerse el sombrero lo tenga cerca y le persiga si se levanta o agacha

2024-05-13 18:14 UTC, sukifree approved these changes
Vale ya está bien, igualmente para que no hayan 2 escenas iguales (PlayerVR y Sockets Interactors) elimina el de PlayerVR que no la estás actualizando.
Por mi parte ok.

2024-05-15 15:05 UTC, merged