Feature/cristobal
miquelg3/GDDProjecte3D pull request #29
Opened 2024-05-13 16:24 UTC by Crisstxt

Animaciones y sistema de combate, IA básica de enemigo hecho, Parte del combate como las animaciones y modelos para que el jugador no los lleve "volando" lo perfeccionare en una rama aparte en esta semana

2024-05-13 16:34 UTC, Ezterothz commented
Hay tantos cambios y tan diversos que no se como meterle mano y saber si esta bien o no

2024-05-13 17:09 UTC, SorakiShirotsubasa requested changes
- No se puede aprobar el pullrequest, porque modificas archivos de Miquel en los cuales esta trabajando actualmente y no ha hecho PR aun, poneos de acuerdo y subidlo de forma adecuada

2024-05-13 17:55 UTC, sukifree commented
Necesito saber qué escena puedo probar (o prefab).

2024-05-13 18:29 UTC, sukifree requested changes
Sin escena o prefab que nos digas, no podemos probar ni aceptar la rama.

2024-05-14 08:29 UTC, Crisstxt commented
Tengo dentro de prebafbs una escena de combate: \Prefabs\CombatePrueba\Escena

2024-05-15 15:13 UTC, miquelg3 approved these changes
Funciona bien

2024-05-15 15:25 UTC, SorakiShirotsubasa approved these changes

2024-05-15 15:34 UTC, merged