Feat:Añadiendo el outline a Prefabs/scene1/Shaders
miquelg3/GDDProjecte3D pull request #35
Opened 2024-05-17 13:37 UTC by SorakiShirotsubasa

Añadiendo el Outline para los objetos interactuables a prefabs/scene1/Shaders

2024-05-19 18:38 UTC, Ezterothz reviewed
No se como quedaste al final con alejandro con lo de la distancia de activacion del shader y lo de que solo se modifique cuando lo apuntes con el raycast de los mandos de VR.

Con lo que digais te reviso el PR

2024-05-19 22:03 UTC, sukifree commented on Unity/BrokenFaith/Assets/Prefabs/Puzzle1/PruebaPalancas.unity
Veo que esta escena se ha editado cuando no ha tenido cambios, realiza un reset de este fichero.

2024-05-19 22:05 UTC, sukifree requested changes
Elimina el cambio de la escena ya que no se ha actualizado. 
Si has utilizado el material en esta escena, genera una escena para el material y haz reset. 

Revisad que el outline con el shadergraph funcione en VR 100% (debería, pero vayamos sobre seguro).

2024-05-21 15:42 UTC, SorakiShirotsubasa commented
He añadido una escena de prueba para comprobar que se vea correctamente en VR, al ver que se detectaba desde muy lejos he bajado la distancia a 3 pies

2024-05-21 16:18 UTC, Ezterothz approved these changes
Yo creo que así ya funciona bien, recuerda mergearte la main antes de subirlo y limpiar los Build settings para que estén las escenas correctas

2024-05-21 17:11 UTC, merged